
# ------------------------------------------------
# Install LetsEncrypt and generate certificates
# ------------------------------------------------
- name: Generate SSL Certificates using LetsEncrypt
  hosts: 
    - web
  vars_files:
    - vars/web.yml
  roles:
    - letsencrypt
  tags: 
    - letsencrypt
  
