- name: Prepare server
  hosts: miarec
  vars_files:
    - ./vars/postgresql.yml
    - ./vars/python.yml
    - ./vars/redis.yml
    - ./vars/apache.yml
    - ./vars/iptables.yml
  become: yes
  roles:
    - {role: 'disable-selinux', tags: 'disable-selinux' }
    - {role: 'postgresql', tags: 'postgresql' }
    - {role: 'python', tags: 'python' }
    - {role: 'redis', tags: 'redis' }
    - {role: 'apache', tags: 'apache' }
    - {role: 'iptables', tags: 'iptables' }

