# ------------------------------------------------
# Deploy MiaRec Web UI and celery task manager
# ------------------------------------------------
- name: Deploy MiaRec Web application
  hosts:
    - web
    - celery
    - celerybeat
  vars_files:
    - vars/db.yml
    - vars/web.yml
  pre_tasks:
    - include_vars: vars/custom.yml
      failed_when: false

    - set_fact:
        miarecweb_db_host: "{{ db_host_service if db_host_service is defined else hostvars[groups.db.0].private_ip_address }}"
        miarecweb_redis_host: "{{ redis_host_service if redis_host_service is defined else hostvars[groups.redis.0].private_ip_address }}"
        miarecweb_install_apache: "{{ 'web' in group_names }}"
        miarecweb_install_celeryd: "{{ 'celery' in group_names }}"
        miarecweb_install_celerybeat: "{{ 'celerybeat' in group_names }}"
    - debug: var=miarecweb_db_host
    - debug: var=miarecweb_redis_host
  roles:
    - role: 'miarecweb'
  tags: 'miarecweb'


# ------------------------------------------------
# Deploy MiaRec recorder
# ------------------------------------------------
- name: Deploy MiaRec Recorder application
  hosts: recorder
  vars_files:
    - vars/db.yml
  pre_tasks:
    - include_vars: vars/custom.yml
      failed_when: false

    - set_fact:
        miarec_db_host: "{{ db_host_service if db_host_service is defined else hostvars[groups.db.0].private_ip_address }}"
        miarec_redis_host: "{{ redis_host_service if redis_host_service is defined else hostvars[groups.redis.0].private_ip_address }}"
        miarec_http_call_events_host: "{{ hostvars[groups.web.0].private_ip_address }}"
        miarec_rest_api_permitted_hosts: "{{ groups['web'] | map('extract', hostvars, ['private_ip_address']) | join(';') }}"

    - debug: var=miarec_db_host
    - debug: var=miarec_redis_host
    - debug: var=miarec_http_call_events_host
    - debug: var=miarec_rest_api_permitted_hosts
  roles:
    - role: 'miarec'
  tags: 'miarec'

# ------------------------------------------------
# Deploy MiaRec Screen Controller
# ------------------------------------------------
- name: Deploy MiaRec Screen Controller
  hosts: screen
  vars_files:
    - vars/db.yml
  pre_tasks:
    - include_vars: vars/custom.yml
      failed_when: false

    - set_fact:
        miarec_db_host: "{{ db_host_service if db_host_service is defined else hostvars[groups.db.0].private_ip_address }}"
        miarec_redis_host: "{{ redis_host_service if redis_host_service is defined else hostvars[groups.redis.0].private_ip_address }}"
        miarec_rest_api_permitted_hosts: "{{ groups['web'] | map('extract', hostvars, ['private_ip_address']) | join(';') }}"

    - debug: var=miarec_db_host
    - debug: var=miarec_redis_host
    - debug: var=miarec_rest_api_permitted_hosts
  roles:
    - role: 'miarec-screen'
  tags: 'miarec-screen'
