---
- name: Converge
  hosts: all
  # become: true

  pre_tasks:

    - name: Set Install Variables
      set_fact:
        private_ip_address: 127.0.0.1
        miarecweb_secret: "{{ lookup('env', 'MIARECWEB_SECRET') }}"
        miarecweb_version: "{{ lookup('env', 'MIARECWEB_VERSION') }}"
        miarec_version: "{{ lookup('env', 'MIAREC_VERSION') }}"
        miarec_screen_version: "{{ lookup('env', 'MIAREC_SCREEN_VERSION') }}"
        miarec_livemon_version: "{{ lookup('env', 'MIAREC_LIVEMON_VERSION') }}"
        postgresql_version: "{{ lookup('env', 'POSTGRESQL_VERSION') }}"
        install_pgbouncer: "{{ lookup('env', 'PGBOUNCER_INSTALL') }}"
        python_version: "{{ lookup('env', 'PYTHON_VERSION') }}"
        # Use system packages instead of compiling from source
        redis_install_from_source: false
        python_install_from_source: false
        sox_install_from_source: false

- name: Run prepare-hosts playbook
  import_playbook: ../../prepare-hosts.yml

- name: Run setup-miarec playbook
  import_playbook: ../../setup-miarec.yml
