---
# All components on one container.
- name: Set install variables
  import_playbook: ../shared/install-vars.yml

- name: Run prepare-hosts playbook
  import_playbook: ../../prepare-hosts.yml

- name: Run setup-miarec playbook
  import_playbook: ../../setup-miarec.yml
