---
- name: Converge
  hosts: all
  # become: true

  pre_tasks:

    # required for miarecweb.yml - `Install dependencies (requirements.txt)`
    - name: Prepare Host | CentOS
      when: ansible_distribution == "CentOS"
      block:
        - name: Install EPEL
          package:
            name: epel-release
            state: present

        - name: Install pip
          package:
            name: python-pip
            state: present


    - name: Prepare Host | RHEL 7
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution_major_version == "7"
      block:

        # `llvm-toolset-7-clang` and 1`llvm5.0-devel` are a requirement for PostgreSQL on RHEL7
        # these would be provided by repository `rhel-server-rhscl-7-rpms`,
        # the UBI based docker image uses CentOS repositories,
        # Those pacakages are available in `centos-release-scl` and `epel-release`
        # in standard runs of this role, this step would not be required
        - name: Install prerequisites | RHEL 7
          yum:
            name: "{{ item }}"
          with_items:
            - centos-release-scl
            - epel-release

        # CentOS repository and UBI repository have mismatched versions of httpd
        # this causes and issue with httpd-devel is installed from CentOS repository
        # disabling UBI repository to force install from CentOS repository
        - name: Disable ubi-7 repository | RHEL 7
          command: yum-config-manager --disable ubi-7
          changed_when: false


    - name: Set Install Variables
      set_fact:
        private_ip_address: 127.0.0.1
        miarecweb_secret: "{{ lookup('env', 'MIARECWEB_SECRET') }}"
        miarecweb_version: "{{ lookup('env', 'MIARECWEB_VERSION') }}"
        miarec_version: "{{ lookup('env', 'MIAREC_VERSION') }}"
        miarec_screen_version: "{{ lookup('env', 'MIAREC_SCREEN_VERSION') }}"
        miarec_livemon_version: "{{ lookup('env', 'MIAREC_LIVEMON_VERSION') }}"
        postgresql_version: "{{ lookup('env', 'POSTGRESQL_VERSION') }}"
        install_pgbouncer: "{{ lookup('env', 'PGBOUNCER_INSTALL') }}"
        python_version: "{{ lookup('env', 'PYTHON_VERSION') }}"
        redis_version: "{{ lookup('env', 'REDIS_VERSION') }}"

- name: Run prepare-hosts playbook
  import_playbook: ../../prepare-hosts.yml

- name: Run setup-miarec playbook
  import_playbook: ../../setup-miarec.yml
