---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ghcr.io/miarec/${MOLECULE_DISTRO:-ubuntu2204}-systemd:latest
    groups:
      - recorder
      - livemon
      - screen
      - db
      - redis
      - web
      - celery
      - celerybeat
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  env:
    ANSIBLE_VERBOSITY: ${MOLECULE_ANSIBLE_VERBOSITY:-0}
    MIARECWEB_VERSION: ${MOLECULE_MIARECWEB_VERSION:-"2024.5.13.0"}
    MIARECWEB_SECRET: ${MOLECULE_MIARECWEB_SECRET:-"secret"}
    MIAREC_VERSION: ${MOLECULE_MIAREC_VERSION:-"2024.6.2.0"}
    MIAREC_SCREEN_VERSION: ${MOLECULE_MIAREC_SCREEN_VERSION:-"2024.6.2.0"}
    MIAREC_LIVEMON_VERSION: ${MOLECULE_MIAREC_LIVEMON_VERSION:-"0.1.0.183"}
    PYTHON_VERSION: ${MOLECULE_PYTHON_VERSION:-"3.11.7"}
    POSTGRESQL_VERSION: ${MOLECULE_POSTGRESQL_VERSION:-"12"}
    PGBOUNCER_INSTALL: ${MOLECULE_PGBOUNCER_INSTALL:-"true"}
    REDIS_VERSION: ${MOLECULE_REDIS_VERSION:-"5.0.14"}

verifier:
  name: testinfra
  options:
    s: true
    verbose: true