---
# The decoupled scenario with the TLS variables of the tls scenario.
- name: Set install variables
  import_playbook: ../shared/install-vars.yml

- name: Set the container address
  import_playbook: ../shared/container-address.yml

- name: Set TLS variables
  import_playbook: ../shared/tls-vars.yml

- name: Run prepare-hosts playbook
  import_playbook: ../../prepare-hosts.yml

- name: Run setup-miarec playbook
  import_playbook: ../../setup-miarec.yml
